### ISSUE TITLE
Chakra UI Toasts doesn't work.

### ISSUE THREAD

**Issue by dismalDarko** [horizon-ui/horizon-ui-chakra#17]
Hello, i've tried using toasts from chakra ui on this template but for some reason, even on a simple test like

```

 <Button
      onClick={() =>
        toast({
          title: 'Account created.',
          description: "We've created your account for you.",
          status: 'success',
          duration: 9000,
          isClosable: true,
        })
      }
    >
      Show Toast
    </Button>
```

I get this error when i click the button
: 
![image](https://user-images.githubusercontent.com/57333787/194676028-73f9a395-a6b4-4b2b-bc1c-c1da42598596.png)

**Comment by Mekolaos** [comment]
Hello, can confirm that it Chakra toasts don't work on this template. The exact same error shows up on my end.

**Comment by simmmpleweb** [comment]
Hello, @dismalDarko ! Thanks for using our produt and sorry for the late response ! The problem is from the Theme Editor used in this version. We will talk with the makers of the plugin and leave a message when solved! You can simply remove the theme editor and the toast perfectly works. Regards, Vlad.
